# Generated by Django 4.2.2 on 2023-07-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_article_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
