# Generated by Django 4.2.2 on 2023-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
