# Generated by Django 4.2.2 on 2023-07-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_article_image_url_article_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='color',
        ),
        migrations.AddField(
            model_name='article',
            name='colors',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
