# Generated by Django 4.2.2 on 2023-07-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
