# Generated by Django 4.2.2 on 2023-07-25 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_article_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ranking_global',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ranking_user',
        ),
        migrations.AddField(
            model_name='article',
            name='promo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='article',
            name='stock_L',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='stock_M',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='stock_S',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='stock_XL',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='stock_XS',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
