# Generated by Django 4.2.2 on 2023-07-27 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_article_main_category_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
