# Generated by Django 4.2.2 on 2023-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_article_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_added',
        ),
    ]
