# Generated by Django 4.2.2 on 2023-07-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
