# Generated by Django 4.2.3 on 2023-07-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_article_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='app.partners'),
        ),
    ]
