# Generated by Django 4.2.3 on 2023-07-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_profile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wishlist',
        ),
    ]
