# Generated by Django 4.2.3 on 2023-07-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
