# Generated by Django 4.2.2 on 2023-07-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rating_delete_articlerating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
