# Generated by Django 4.2.2 on 2023-07-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_article_fake_reviews_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fake_reviews_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reviews_count',
        ),
    ]
